# Starting with base image
FROM python:3.11-slim

# Copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# Switch working directory
WORKDIR /app

# Install the dependency packages from requirements file
RUN pip3 install -r requirements.txt

# Copy every content from the local file to the Image
COPY . /app

# Configure the container to run in an executed manner
EXPOSE 8080
CMD ["python3","hello.py"]
